# Generated by Django 4.2.1 on 2023-06-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=12)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('id_mecanico', models.IntegerField()),
                ('nombre_mecanico', models.CharField(max_length=50)),
                ('nombre_cli', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('telefono_cliente', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='makween_app.estado_atencion')),
            ],
        ),
    ]
