# Generated by Django 4.2.2 on 2023-06-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makween_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=12)),
                ('mensaje', models.CharField(max_length=400)),
            ],
        ),
    ]
