# Generated by Django 4.2.1 on 2023-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makween_app', '0003_atencion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='atenciones'),
        ),
    ]
