# Generated by Django 4.2.1 on 2023-06-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makween_app', '0005_alter_atencion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_atencion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='atencion',
            name='descripcion_estado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
