# Generated by Django 4.2.1 on 2023-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makween_app', '0007_remove_contactos_id_contactos_id_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='mecanico',
            fields=[
                ('id_meca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='mecanico')),
            ],
        ),
        migrations.AlterField(
            model_name='contactos',
            name='id_contacto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
